### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by einacio** [navill/DJANGO_EXAMPLE#1]
hi there. is that your gmail password on a public repo?

https://github.com/navill/DJANGO_EXAMPLE/blob/d3b3e651d865d9aa946ade8d5b2eebe8c7d8096c/blog_application/mysite/mysite/settings.py#L132

found with https://shhgit.darkport.co.uk/

**Comment by ochilan** [comment]
Hehe, also found that file through shhgit. ^^ Good thing that there is two-factor auth.

**Comment by navill** [comment]
changed password
